### ISSUE TITLE
Site isn't live on GH Pages

### ISSUE THREAD

**Issue by park-junha** [btphan95/btphan95.github.io#1]
![Screen Shot 2020-05-20 at 5 41 52 PM](https://user-images.githubusercontent.com/48537888/82511151-627dd200-9ac1-11ea-870e-24cf0ed136e0.png)

**Comment by btphan95** [comment]
Appreciate the tip @park-junha.

It looks like something broke a few hours ago (possible that it's because I tried making my repo private, and [Github doesn't publish private repos](https://stackoverflow.com/questions/28744980/github-pages-for-private-repository).

It's live now!
